# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eat A Rainbow Website Tech Blog
email: ben@eatarainbow.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Tech talk for [eatarainbow.org.uk](http://www.eatarainbow.org.uk)
baseurl: "/nxfc" # the subpath of your site, e.g. /blog
url: "http://newcrossfoodcoop.github.io" # the base hostname & protocol for your site
github_username: bsimpson53
gitter_username: newcrossfoodcoop/nxfc 
# Build settings
markdown: kramdown
